name: Flutter Integration Tests

on:
  push:
    branches:
      - base-level-1-app-development-with-riverpod
  pull_request:
    branches:
      - main
      - master

jobs:
  integration-test:
    name: Run Integration Tests on Android Emulator
    runs-on: macos-13 # macos-13 is Intel-based, which supports x86_64 Android emulators (macos-latest is ARM)

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'

      - name: Install Dependencies
        run: flutter pub get

      - name: Run Integration Tests on Android Emulator
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 29
          target: default
          arch: x86_64
          profile: Nexus 6
          disable-animations: true
          emulator-options: -no-snapshot-save -no-window -gpu swiftshader_indirect -noaudio -no-boot-anim -camera-back none
          script: flutter test integration_test/auth_flow_test.dart
